spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:fastAdmin}?useunicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:root}
    druid:
      maxActive: 10
      initialSize: 1
      minIdle: 1
      maxWait: 60000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      filters: stat, wall
      validationQuery: select 'x'
      poolPreparedStatements: true
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=50000
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎


  #配置redis数据库连接
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    jedis:
      pool:
        max-idle: 20
        min-idle: 1
        max-active: 20
    database: 0 #默认是索引为的0的数据库
    password:

  # 文件上传
  servlet:
    multipart:
      enabled: true
      location: ./file/
      file-size-threshold: 5MB
      max-file-size: 20MB

# 屏蔽 包 输出日志(示例)
logging:
  level:
    org.fei.admin.app.dto: 'off'
  pattern:
    level:


